#!/usr/bin/python3
import itertools
import sys
def bruteforce(charset, length):
    return itertools.product(charset, repeat=length)

prefixes = ['', 'vo/', 'sys/mode/cg/', 'script/', 'scripts/']
suffixes = ['', '.tlg', '.dat', '.png', '.txt']
suffixes = ['']
prefixes = ['']

def infix_generator():
    for x in open('strings.lst', 'r'):
        yield x.strip()
    for x in bruteforce(list('abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_-'), 1):
        yield ''.join(x)

for suffix in suffixes:
    suffix += "\n"
    for prefix in prefixes:
        for infix in infix_generator():
            sys.stdout.buffer.write((prefix + infix + suffix).encode('sjis'))
